
services:
  grafana:
    image: grafana/grafana-oss:11.3.4
    container_name: grafana
    environment:
      - TERM=linux
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel

    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: finly-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    container_name: finly-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
    volumes:
      - pgadmindata:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: always

volumes:
  grafana_storage:
  pgdata:
  pgadmindata:
